1>------ Build started: Project: fax, Configuration: Debug Win32 ------
1>Build started 2013/11/28 11:17:28.
1>ClCompile:
1>  fax2bmp.cpp
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(139): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(234) : see declaration of 'fopen'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(143): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(234) : see declaration of 'fopen'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(184): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(234) : see declaration of 'fopen'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(185): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(234) : see declaration of 'fopen'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(247): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(234) : see declaration of 'fopen'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(301): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(234) : see declaration of 'fopen'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(316): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(234) : see declaration of 'fopen'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(372): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(234) : see declaration of 'fopen'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(437): error C2039: 'one' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(437): error C2039: 'zero' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(439): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(441): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(444): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(448): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(449): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(456): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(507): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(515): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(568): error C2039: 'one' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(568): error C2039: 'zero' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(570): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(572): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(575): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(579): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(580): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(594): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(597): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(633): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(642): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(667): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(727): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(739): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1093): error C2039: 'one' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1093): error C2039: 'zero' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1095): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1097): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1101): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1105): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1106): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1119): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1137): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1167): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1177): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>d:\我的资料库\documents\visual studio 2010\projects\fax\fax\fax2bmp.cpp(1205): error C2039: 'run_len' : is not a member of 't4node'
1>          d:\我的资料库\documents\visual studio 2010\projects\fax\fax\my.h(27) : see declaration of 't4node'
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:00.75
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
